packages:
  - "apps/*"
  - "libs/*"
catalog:
  react: ^19.1.0
  react-dom: ^19.1.0
  typescript: ^5.8.3
  "@types/node": ^24.0.4
  "@types/react": ^19.1.8
  "@types/react-dom": ^19.1.6
  "@dotenvx/dotenvx": ^1.45.1
  "@react-router/dev": 7.6.0
  "@react-router/node": 7.6.2
  "react-router": 7.6.2
  "react-router-hono-server": ^2.13.0
  hono: ^4.7.11
  isbot: ^5.1.28
  vite: ^6.3.5
  vite-tsconfig-paths: ^5.1.4
